name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest
    container: cypress/browsers:latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run-pipeline

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-execution-report
          path: |
            cypress/reports/mocha
            cypress/screenshots
          retention-days: 10